name: Build LacOS ISO
on: 
  workflow_dispatch: # Allows you to start it manually
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y squashfs-tools genisoimage

      - name: Run LacOS Build Script
        run: bash build.sh

      - name: Upload LacOS ISO
        uses: actions/upload-artifact@v4
        with:
          name: LacOS-Sequoia-ISO
          path: LacOS-Sequoia.iso
